use crate::kernel::global::{ FIXED_PIXEL_SHADERS, FIXED_VERTEX_SHADERS, MATERIAL_LISTS, RENDER_LISTS, RENDER_STATES, SCENE_LISTS, SHADER_SOURCE };
use crate::kernel::init::VideoMode;
use crate::utility::item_array::ItemArray;
use crate::utility::mutex::RecursiveMutex;
use glam::Vec2;

include!("graphics_common.rs");

#[repr(C)]
#[derive(Debug)]
pub struct GraphicsStateSteam {
    flags: GraphicsFlags,
    video: VideoMode,
    fps: u32,
    fvf: u32,
    pub(super) scene: [*mut u8; SCENE_LISTS],
    pub(super) cmd_buffer: *mut u8,
    texture_head: *mut u8,
    texture_mutex: RecursiveMutex,
    config_button_resources: *mut u8,
    material_array_stack: [*mut ItemArray<usize>; MATERIAL_LISTS],
    material_array_count: u32,
    material_mutex: RecursiveMutex,
    shader_vtx_head: [*mut u8; SHADER_SOURCE],
    shader_vtx_mutex: RecursiveMutex,
    shader_frg_head: [*mut u8; SHADER_SOURCE],
    shader_frg_mutex: RecursiveMutex,
    shader_geo_head: *mut u8,
    shader_geo_mutex: RecursiveMutex,
    shader_cmp_head: *mut u8,
    shader_cmp_mutex: RecursiveMutex,
    fieldac0_head: *mut u8,
    fieldac0_mutex: RecursiveMutex,
    asset_head: *mut u8,
    asset_mutex: RecursiveMutex,
    asset_editor_mode: bool,
    pub(super) ot_shadow_list: [*mut u8; RENDER_LISTS],
    pub(super) ot_render_list: [*mut u8; RENDER_LISTS],
    pub(super) ot_prepare_list: [*mut u8; RENDER_LISTS],
    pub(super) ot_cull_object: *mut u8,
    pub(super) prio_max: u32,
    ot: *mut u8,
    prio_group_max: u32,
    pub(super) frame_id: u32,
    widget_prio: u32,
    dbg_fnt_prio: u32,
    mouse_prio: u32,
    resources: *mut u8,
    setup: *mut u8,
    render_info: [[*mut u8; 2]; 2],
    exist: [u32; 2],
    render_state_current: [usize; RENDER_STATES],
    render_state_stack: [[usize; 2]; RENDER_STATES],
    shader_source: [[*mut u8; 3]; SHADER_SOURCE],
    shader_vertex: [*mut u8; FIXED_VERTEX_SHADERS],
    shader_vertex_end: *mut u8,
    shader_fragment: [*mut u8; FIXED_PIXEL_SHADERS],
    shader_fragment_end: *mut u8,
    shader_geometry: *mut u8,
    shader_compute: [*mut u8; 7],
    shader_compute_end: *mut u8,
    current_shader_vertex: *mut u8,
    current_shader_fragment: *mut u8,
    current_shader_geometry: *mut u8,
    current_shader_compute: *mut u8,
    shader_id_flag_mask: [[u32; 3]; 3],
    field2334: [u8; 44],
    shader_cache_mutex: RecursiveMutex,
    field2388: *mut u8,
    effect_vertex_indices: [*mut u8; 6],
    light_placement: [*mut u8; 2],
    ascii_font_texture: *mut u8,
    shader_outline_texture: *mut u8,
    shader_noise_texture: *mut u8,
    shader_edge_dark_texture: *mut u8,
    environment: [u8; 0x280],
    image_path: [u8; 0x400],
    adjustment: Vec2,
    fullscreen_render_target: *mut u8,
    field2a80: [u8; 0x140]
}